[2610610]
locoClassName = "com.kakao.talk.loco.net.server.LocoClient"
locoRequestMethod = "o"
locoResponseMethod = "j"

locoProtocolClass = "com.kakao.talk.loco.protocol.d"
locoHeaderClass = "com.kakao.talk.loco.protocol.b"
locoBodyClass = "com.kakao.talk.loco.protocol.LocoBody"
locoMethodClass = "com.kakao.talk.loco.protocol.c"

locoGetHeaderField = "a"
locoGetBodyField = "c"

locoPacketIdField = "a"
locoStatusField = "b"
locoMethodField = "c"

locoMethodBytesMethod = "getMethodBytes"
locoMethodNameMethod = "getMethodName"

locoBodyToMapMethod = "q"
locoBodyBSONObjectField = "a"
locoBodyBSONToMapMethod = "toMap"

locoReqClass = "l71.a"
locoResClass = "l71.b"

chatTypeClass = "y30.a"
chatTypeFinderClass = "y30.a$a"
chatTypeFinderFindMethod = "a"

chatSendingLogClass = "com.kakao.talk.manager.send.sending.ChatSendingLog"
chatSendingLogBuilderClass = "com.kakao.talk.manager.send.sending.ChatSendingLog$b"

chatSendingLogBuilderMessageProperty = "d"
chatSendingLogBuilderAttachmentProperty = "c"
chatSendingLogBuilderPhotosProperty = "l"
chatSendingLogBuilderBuildMethod = "a"

chatSendingLogRequestClass = "com.kakao.talk.manager.send.ChatSendingLogRequest"
chatSendingTypeClass = "com.kakao.talk.manager.send.ChatSendingLogRequest$c"

# chatLogSendingMethod = "r"
chatLogSendingMethod = "j"

chatRoomClass = "f30.h"

chatRoomListManagerClass = "f30.z0"
chatRoomListRealManagerClass = "f30.z0$a"

chatRoomListManagerProperty = "q"
chatRoomListRealProperty = "d"

chatRoomChannelIdField = "c"

chatRoomLinkIdField = "N"

chatRoomTypeMethod = "T"

chatRoomNameMethod = "S"

chatRoomMemberSetMethod = "J"

parseChannelIdMethod = "m"

sendEventHandlerClass = "com.kakao.talk.manager.send.q"

chatMemberSetClass = "c50.j"
chatMemberSetWatermarkManagerField = "e"

chatRoomTypeClass = "i30.b"

watermarkClass = "c50.j0"
watermarkMemberListField = "a"

oauthHelperClass = "re1.a"
oauthHelperStaticClass = "m91.a$a"
oauthHelperStaticInstanceField = "a"
oauthHelperGetTokenMethod = "a"
oauthHelperGetAuthorization = "d"

hardwareClass = "op1.k1"
hardwareInstanceField = "a"
hardwareGetDeviceUUIDMethod = "j"

chatLogClass = "a50.c"

chatLogLogIdField = "b"
chatLogChatIdField = "e"
chatLogTypeField = "c"
chatLogAuthorIdField = "f"
chatLogAttachmentField = "l"
chatLogMessageField = "g"
chatLogSendAtField = "m"
chatLogMessageIdField = "o"
chatLogPrevIdField = "s"
chatLogRefererField = "v"
chatLogSupplementField = "x"

photoModelClass = "com.kakao.talk.manager.send.sending.ChatSendingLog$f"
talkPreferencesQualityDataClass = "ln1.d$a"
talkPreferencesQualityFinderClass = "ln1.d$a$a"
talkPreferencesQualityFinderMethod = "a"